name: poky-container build and test
on:
  push:
    branches:
      - master
  pull_request:

  # Allow for manually running
  workflow_dispatch:

  # Run at 01:42 UTC every Saturday
  schedule:
    - cron: '42 1 * * 6'

jobs:
  build-test-deploy:
    runs-on: ubuntu-24.04-2core-arm64
    permissions:
      packages: write
    strategy:
      fail-fast: false
      matrix:
        base_distro: [
          debian-12,
        ]
        targetplatform: [
          linux/arm64
        ]        
    env:
      BASE_DISTRO: ${{ matrix.base_distro }}
      TARGETPLATFORM: ${{ matrix.targetplatform }}
      REPO_URL: ghcr.io      
      REPO: jackpocket/crops/poky
      DEFAULT_DISTRO: debian-12
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GHCR_USERNAME: ${{ github.actor }}
      GHCR_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      # Build and test the images
      - name: Run build-and-test.sh
        run: ./build-and-test.sh

      # Deploy the images
      - name: Deploy
        run: bash deploy.sh
